AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless S3 Lambda SQS V2

Parameters:
  SQSQueueName:
    Type: String
    Default: lab-practice-101-s3-lambda-sqs-v2-queue
  StageRegion:
    Type: String
    Default: ap-northeast-1

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:*
                Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${SQSQueueName}

  ACLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: acHandler.handler
      Runtime: nodejs18.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref SQSQueueName
          STAGE_REGION: !Ref StageRegion

  RCLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: rcHandler.handler
      Runtime: nodejs18.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref SQSQueueName
          STAGE_REGION: !Ref StageRegion

Outputs:
  ACLambdaFunction:
    Value: !GetAtt ACLambdaFunction.Arn
  RCLambdaFunction:
    Value: !GetAtt RCLambdaFunction.Arn
