AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless S3 Lambda SQS V2

Parameters:
  SQSQueueName:
    Type: String
    Default: lab-practice-101-s3-lambda-sqs-v2-queue
  StageRegion:
    Type: String
    Default: ap-northeast-1
  ACBucketName:
    Type: String
    Default: lab-practice-101-s3-lambda-sqs-v2-queue-ac-bucket
  RCBucketName:
    Type: String
    Default: lab-practice-101-s3-lambda-sqs-v2-queue-rc-bucket

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:*
                Resource: !GetAtt SQSQueue.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${ACBucketName}
                  - !Sub arn:aws:s3:::${ACBucketName}/*
                  - !Sub arn:aws:s3:::${RCBucketName}
                  - !Sub arn:aws:s3:::${RCBucketName}/*

  SQSQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Retain
    Properties:
      QueueName: !Ref SQSQueueName

  ACLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: acHandler.handler
      Runtime: nodejs18.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref SQSQueueName
          STAGE_REGION: !Ref StageRegion

  RCLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: rcHandler.handler
      Runtime: nodejs18.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref SQSQueueName
          STAGE_REGION: !Ref StageRegion

  ACLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ACLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:s3:::${ACBucketName}

  RCLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt RCLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:s3:::${RCBucketName}

  ACBucketNotification:
    Type: AWS::S3::BucketNotification
    Properties:
      Bucket: !Ref ACBucketName
      LambdaConfigurations:
        - Event: s3:ObjectCreated:*
          Function: !GetAtt ACLambdaFunction.Arn

  RCBucketNotification:
    Type: AWS::S3::BucketNotification
    Properties:
      Bucket: !Ref RCBucketName
      LambdaConfigurations:
        - Event: s3:ObjectCreated:*
          Function: !GetAtt RCLambdaFunction.Arn

Outputs:
  SQSQueueURL:
    Value: !GetAtt SQSQueue.Arn
  ACLambdaFunctionName:
    Value: !Ref ACLambdaFunction
  RCLambdaFunctionName:
    Value: !Ref RCLambdaFunction
  LambdaExecutionRoleArn:
    Value: !GetAtt LambdaExecutionRole.Arn
